version: '3.8'

services:
  # Основное приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketing-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/marketingdb
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - uploads:/app/uploads

  # База данных PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: marketing-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marketingdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Веб-сервер для продакшн (при необходимости)
  # Этот сервис можно раскомментировать для запуска в продакшн-среде 
  # nginx:
  #   image: nginx:alpine
  #   container_name: marketing-nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  uploads: